# Conclusion

We focused on the beginning of pandemic period by focusing on the speeches of both politicians in March. After having downloaded 3 speeches of Emmanuel Macron and 7 speeches of Boris Johnson, using Xpath, our Exploratory Data Analysis points out specificities among the UK and French supervised. In spite of the shortness of the Boris Johnson’s words, the vocabulary used by the Brititish Price Minister is richer than the allocutions of the French President. The French President speaks more about the future, by using  at a high frequency the auxiliary «will», whereas the Prime Minister is more balanced in the words used, linking present and future and integrating social terms like family and friends.

The Sentiment Analysis outlines more positive discourses coming from across the Channel, the speech on March 12th being the more positive than the others. The specificity of Emmanuel Macron’s structure is its stability: his allocutions follow an almost similar distribution of the sentiment, and this trend is not affected by the length of his speeches. By using the «nrc», «afinn» and «LSD2015», the qualitative ad quantitative-based results differs, but 3 stages out of the 4 are convergent, fortifying those results.

The Similarity analysis was not significant: the results highlight no similarities among speeches of the same president. Some investigations might be needed in order to understand the roots of this outcome. The Word Embedding presents clusters in a seemingly chronological order for Boris Johnson, grouping step by step the 1rst speech to the later, while the respective Macron’s dendogram groups the 1rst and 3rd discourses together, joining ultimately the second one. Topic Modelling’s insights for the texts per politician has no added value: speaking of the same subject and in the same way, the discourses overlap each other by sharing certain similar topics. However, when combining French and British discourses, the Topic Modelling gives a clearer vision on the difference of topics mentioned. We note that the joint analysis leads to better quality results.

Finally, after identifying some discriminatory features among speeches, we built a supervised learner to categorize random speeches as belonging to Emmanuel Macron ou Boris Johnson, using a random forest model. It is based on the division of the speeches by sentence. Our classification model is biased as predicting too much False Negative (sentences erroneously categorized as belonging to Emmanuel Macron). An attempt for improvement by increasing the number of features was satisfactory, increasing slightly the accuracy while keeping the overestimation of President Macron’s sentences. Further improvements might be operated by weighting the independent variables in order to reduce the bias.

To conclude, our basis assumption of similarity of the construction of sentences and of the goal of such discourses might be correct. In addition to the similar subject (pandemic measures), the basis assumption could be a cause of the lukewarm results in Topic Modeling, Word Embedding and Similarity, limiting the potentiality of discriminatory features. The speeches differ greatly in length, vocabulary and sentiments, but those differences are not as strong as needed for building a satisfactory random forest classification learner. The project might be leveled up by adding new speeches (taking a larger period of time) and rethinking our supervised learner to be based on more accurate independent variables, assessed by a statistical analysis and investigation on the p-values.